name: test_webhook

services:
    latest:
        image: test_webhook
        ports:
            - 80:80
        environment:
            - WEB_CONCURRENCY=1
        restart: always
        secrets:
            - gh_web_hook_secret
        build: .
        volumes:
            - type: bind
              source: update
              target: /test_webhook/update

secrets:
  gh_web_hook_secret:
    file: ./gh_web_hook_secret